// ============================================================
// RESTAURANT MENU DATA
// Nguồn: data.js do người dùng cung cấp.
// Được expose qua window.MENU_DATA để Gemini Live đọc trực tiếp
// ở frontend, không cần gọi backend.
// ============================================================

window.MENU_DATA = [
  {
    id: "pho-bo",
    name: "Phở Bò",
    aliases: ["phở bò", "pho bo"],
    price: 60000,
    currency: "VND",
    unit: "phần",
    description: "Phở bò nóng, nước dùng đậm vị, ăn kèm rau thơm.",
    ingredients: [
      "bánh phở",
      "xương bò",
      "thịt bò (nạm, gầu hoặc thịt bò tái)",
      "hành tây",
      "gừng",
      "quế",
      "hoa hồi",
      "thảo quả",
      "hạt mùi",
      "nước mắm",
      "hành lá",
      "rau mùi",
      "rau húng",
      "giá đỗ",
      "chanh",
      "ớt"
    ],
    image: "../image/pho_bo.jpg",
    available: true
  },
  {
    id: "bun-bo-hue",
    name: "Bún Bò Huế",
    aliases: ["bún bò huế", "bun bo hue", "bún bò"],
    price: 70000,
    currency: "VND",
    unit: "phần",
    description: "Bún bò Huế cay nhẹ, nước dùng thơm sả.",
    ingredients: [
      "bún sợi to",
      "xương bò",
      "bắp bò hoặc nạm bò",
      "chân giò heo",
      "sả",
      "mắm ruốc Huế",
      "hành tây",
      "gừng",
      "tỏi",
      "dầu màu điều",
      "sa tế",
      "hành lá",
      "giá đỗ",
      "rau thơm",
      "húng quế",
      "hoa chuối",
      "chanh",
      "ớt",
      "huyết heo hoặc huyết bò (tùy chọn)",
      "chả cua hoặc chả bò (tùy chọn)"
    ],
    image: "../image/bun_bo_hue.png",
    available: true
  },
  {
    id: "com-tam",
    name: "Cơm Tấm",
    aliases: ["cơm tấm", "com tam", "cơm tấm sườn bì chả"],
    price: 55000,
    currency: "VND",
    unit: "phần",
    description: "Cơm tấm sườn nướng, bì, chả và nước mắm.",
    ingredients: [
      "gạo tấm",
      "sườn cốt lết hoặc thịt nạc dăm",
      "bì heo",
      "thịt heo xay",
      "trứng gà",
      "miến",
      "mộc nhĩ",
      "thính gạo",
      "hành lá",
      "cà rốt",
      "củ cải trắng",
      "sả",
      "hành tím",
      "tỏi",
      "ớt",
      "nước mắm",
      "đường",
      "dầu hào",
      "mật ong",
      "mỡ hành",
      "đồ chua"
    ],
    image: "../image/com_tam.jpg",
    available: true
  },
  {
    id: "banh-mi-chao",
    name: "Bánh Mì Chảo",
    aliases: ["bánh mì chảo", "banh mi chao"],
    price: 30000,
    currency: "VND",
    unit: "phần",
    description: "Bánh mì giòn, nhân thịt, pate, rau và nước sốt.",
    ingredients: [
      "bánh mì",
      "thịt bò",
      "thịt heo hoặc sườn cốt lết",
      "pate",
      "xúc xích",
      "trứng gà",
      "hành tây",
      "tỏi",
      "rau mùi",
      "bơ",
      "dầu hào",
      "xì dầu",
      "hạt tiêu",
      "đường",
      "bột năng",
      "nước sốt"
    ],
    image: "../image/banh_mi_chao.jpg",
    available: true
  },
  {
    id: "mi-quang",
    name: "Mì Quảng",
    aliases: ["mì quảng", "mi quang"],
    price: 65000,
    currency: "VND",
    unit: "phần",
    description: "Mì Quảng đậm đà, ăn kèm bánh tráng và rau sống.",
    ingredients: [
      "sợi mì Quảng",
      "thịt gà",
      "thịt ba chỉ",
      "trứng cút",
      "nghệ",
      "hành tăm hoặc hành tím",
      "tỏi",
      "sả",
      "nước mắm",
      "dầu đậu phộng",
      "dầu màu điều",
      "bánh tráng",
      "bắp chuối",
      "giá đỗ",
      "rau húng",
      "rau thơm",
      "hành lá"
    ],
    image: "../image/mi_quang.jpg",
    available: true
  },
  {
    id: "pizza-hai-san",
    name: "Pizza Hải Sản",
    aliases: ["pizza hải sản", "pizza hai san"],
    price: 150000,
    currency: "VND",
    unit: "phần",
    description: "Pizza hải sản phô mai, đế giòn, sốt cà chua.",
    ingredients: [
      "bột mì",
      "men nở",
      "dầu ô liu",
      "sốt cà chua",
      "phô mai",
      "tôm",
      "mực",
      "hành tây",
      "ớt chuông",
      "xúc xích (tùy chọn)",
      "đường",
      "muối"
    ],
    image: "../image/pizza_hai_san.png",
    available: true
  },
  {
    id: "bun-cha",
    name: "Bún Chả",
    aliases: ["bún chả", "bun cha", "bún chả hà nội"],
    price: 45000,
    currency: "VND",
    unit: "phần",
    description: "Bún chả Hà Nội, thơm ngon, đậm vị.",
    ingredients: [
      "bún tươi",
      "thịt ba chỉ",
      "thịt nạc vai",
      "hành khô",
      "hành lá",
      "nước mắm",
      "đường",
      "giấm",
      "hạt tiêu",
      "đu đủ",
      "cà rốt",
      "tỏi",
      "ớt",
      "rau diếp",
      "tía tô",
      "kinh giới",
      "rau mùi",
      "rau thơm"
    ],
    image: "../image/bun_cha.jpg",
    available: true
  },
  {
    id: "goi-cuon",
    name: "Gỏi Cuốn",
    aliases: ["gỏi cuốn", "goi cuon", "gỏi cuốn tôm thịt"],
    price: 45000,
    currency: "VND",
    unit: "phần",
    description: "Gỏi cuốn tôm thịt, rau tươi, chấm sốt đậu phộng.",
    ingredients: [
      "bánh tráng",
      "tôm",
      "thịt heo",
      "bún tươi",
      "hẹ",
      "xà lách",
      "rau húng",
      "tía tô",
      "dưa leo",
      "giá đỗ",
      "đậu phộng",
      "tỏi",
      "ớt",
      "nước mắm hoặc tương chấm",
      "đường",
      "chanh"
    ],
    image: "../image/goi_cuon.jpg",
    available: true
  },
  {
    id: "tra-sua",
    name: "Trà Sữa",
    aliases: ["trà sữa", "tra sua", "trà sữa trân châu"],
    price: 35000,
    currency: "VND",
    unit: "ly",
    description: "Trà sữa thơm béo, có topping trân châu.",
    ingredients: [
      "trà đen hoặc hồng trà",
      "sữa hoặc bột sữa béo",
      "đường",
      "trân châu",
      "bột năng",
      "bột cacao (tùy loại trân châu)",
      "đá"
    ],
    image: "../image/tra_sua.jpg",
    available: true
  },
  {
    id: "ca-phe-sua",
    name: "Cà Phê Sữa",
    aliases: ["cà phê sữa", "ca phe sua", "cà phê sữa đá", "ca phe sua da"],
    price: 30000,
    currency: "VND",
    unit: "ly",
    description: "Cà phê sữa đá đậm vị, phù hợp dùng sau bữa ăn.",
    ingredients: [
      "bột cà phê",
      "nước nóng",
      "sữa đặc",
      "đá"
    ],
    image: "../image/ca_phe_sua.jpg",
    available: true
  }
];

